version: '3.7'

networks:
  nginx-swarm:
    external: true 

services:
  nginx:
    image: nginx:alpine
    ports:
      - '9090:80'
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      timeout: 10s
    networks:
      - "nginx-swarm"
    
